Turntable:
  Turntable: RS232Board5
  IP address: 192.168.5.156
  Step: 0,1
  Static dB: ''
  Target RSSI: 45,60
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.1.101
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.200.102
  LDA-908V-8:
    ip_address: 192.168.10.43
    channels: 1,2,3,8
  model: LDA-908V-8
  step: ''
text_case: test/stability/test_soft_reboot_str.py
debug:
  database_mode: false
  skip_router: false
  skip_corner_rf: false
csv_path: performance_test_csv/ai_wifi_scenarios.csv
