software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
system:
  version: Android 15
  kernel_version: Kernel 6.1
connect_type:
  Android:
    device: ''
  Linux:
    ip: 192.168.208.89
    wildcard: ''
  third_party:
    enabled: false
    wait_seconds: 45
  type: Linux
project:
  customer: Roku
  product_line: TV
  project: Blueplanet
  main_chip: T963D4
  wifi_module: W2
  interface: USB
serial_port:
  baud: '921600'
  port: COM14 (蓝牙链接上的标准串行 (COM14))
  status: false
rvr:
  iperf:
    path: ''
    server_cmd: iperf3 -s -i 1
    client_cmd: iperf3 -c {ip} -i 1 -t 5 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '0'
  tool: iperf
duration_control:
  loop: '2'
  duration_hours: '1.0'
  exitfirst: false
  retry_limit: '0'
router:
  name: asusax88u
  address: 192.168.5.1
  24g_ssid: 24G
  5g_ssid: 5G
