duration_control:
  loop: 1
  duration_hours: null
check_point:
  ping: false
cases:
  test_str:
    ac:
      enabled: false
      on_duration: 5
      off_duration: 5
      port: ''
      mode: NC
    str:
      enabled: true
      on_duration: 15
      off_duration: 15
      port: ''
      mode: 'NO'
  test_swtich_wifi:
    use_router: false
    router_csv: ../Select config csv file
    manual_entries:
    - ssid: sunshine
      security_mode: WPA2-Personal
      password: Home1357
    - ssid: SH-AP-052-2g-xts
      security_mode: Open System
      password: ''
  test_switch_wifi:
    use_router: false
    router_csv: C:\Users\SH171300-1522\PycharmProjects\wifi_test\config\performance_test_csv\rvr_wifi_setup.csv
    manual_entries:
    - ssid: SH-AP-052-2g-xts
      security_mode: Open System
      password: ''
    - ssid: sunshine
      security_mode: WPA2-Personal
      password: Home1357
