corner_angle:
  ip_address: 192.168.5.156
  step:
  - 0
  - 360
  static_db: ''
  target_rssi: 45,60
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.56.75
  LDA-908V-8:
    ip_address: 192.168.5.200
    channels: '1'
  model: RC4DAT-8G-95
  step: 0,75:3
rvr:
  iperf:
    path: ''
    server_cmd: iperf3 -s -i 1
    client_cmd: iperf3 -c {ip} -i 1 -t 30 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '0'
  tool: iperf
router:
  name: asusax88u
  address: 192.168.5.1
text_case: test/performance/test_wifi_peak_throughput.py
debug:
  database_mode: false
  skip_router: true
  skip_corner_rf: false
script_params:
  test__stability__test_str_py:
    ac:
      enabled: true
      on_duration: 5
      off_duration: 5
      port: COM16
      mode: NC
      ping: false
    str:
      enabled: false
      on_duration: 0
      off_duration: 0
      port: ''
      mode: 'NO'
      ping: false
csv_path: performance_test_csv/rvr_wifi_setup_single.csv
