duration_control:
  loop: 2
  duration_hours: null
  exitfirst: true
  retry_limit: 0
check_point:
  ping: true
  ping_targets: www.coco.com
cases:
  test_str:
    ac:
      enabled: false
      on_duration: 5
      off_duration: 5
      port: ''
      mode: NC
    str:
      enabled: true
      on_duration: 15
      off_duration: 15
      port: ''
      mode: 'NO'
  test_switch_wifi:
    use_router: false
    router_csv: performance_test_csv/rvr_wifi_setup_demo.csv
    manual_entries:
    - ssid: SH-AP-052-2g-xts
      security_mode: Open System
      password: ''
    - ssid: sunshine
      security_mode: WPA2-Personal
      password: Home1357
