duration_control:
  loop: null
  duration_hours: null
  exitfirst: false
  retry_limit: 0
check_point:
  ping: true
  ping_targets: 192.168.1.1
cases:
  test_switch_wifi_str:
    ac:
      enabled: true
      on_duration: 0
      off_duration: 0
      port: COM14 (Prolific PL2303GC USB Serial COM Port (COM14))
      mode: 'NO'
    str:
      enabled: true
      on_duration: 0
      off_duration: 0
      port: COM14 (Prolific PL2303GC USB Serial COM Port (COM14))
      mode: 'NO'
    use_router: false
    router_csv: ''
    manual_entries: []
