software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
system:
  version: Android 15
  kernel_version: Kernel 6.1
connect_type:
  Android:
    device: bq2019df11922160b
  Linux:
    ip: 192.168.1.12
    wildcard: ''
  third_party:
    enabled: false
    wait_seconds: 45
  type: Linux
project:
  customer: XIAOMI
  product_line: TV
  project: Blueplanet
  main_chip: T963D4
  wifi_module: W2
  interface: USB
serial_port:
  baud: '9600'
  port: COM14 (蓝牙链接上的标准串行 (COM14))
  status: false
rvr:
  iperf:
    path: ''
    server_cmd: iperf -s -i 1
    client_cmd: iperf -c {ip} -i 1 -t 5 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '0'
  tool: iperf
