software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
system:
  version: Android 15
  kernel_version: Kernel 6.1
connect_type:
  Android:
    device: AV423352N0053
  Linux:
    ip: 192.168.200.101
    wildcard: ''
  third_party:
    enabled: false
    wait_seconds: 45
  type: Android
project:
  customer: ONN
  product_line: IPC
  project: KitKat513
  main_chip: C302X
  wifi_module: W1U
  interface: USB
serial_port:
  baud: '921600'
  port: COM5 (Silicon Labs CP210x USB to UART Bridge (COM5))
  status: true
rvr:
  iperf:
    path: ''
    server_cmd: iperf -s -i 1
    client_cmd: iperf -c {ip} -i 1 -t 5 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '0'
  tool: iperf
