software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
system:
  version: Android 13
  kernel_version: Kernel 5.15
connect_type:
  Android:
    device: '69512800000000611'
  Linux:
    ip: 192.168.56.12
  third_party:
    enabled: false
    wait_seconds: 45
  type: Android
fpga:
  customer: XIAOMI
  product_line: OTT
  project: OB7
  main_chip: S805X3
  wifi_module: W1U
  interface: SDIO
serial_port:
  baud: '961200'
  port: COM5
  status: false
