duration_control:
  loop: ''
  duration_hours: ''
  exitfirst: false
  retry_limit: '2'
check_point:
  ping: false
  ping_targets: 192.168.1.1
cases:
  test_switch_wifi_str:
    ac:
      enabled: false
      on_duration: '0'
      off_duration: '0'
      port: ''
      mode: 'NO'
      relay_type: usb_relay
      relay_params: []
    str:
      enabled: false
      on_duration: '0'
      off_duration: '0'
      port: ''
      mode: 'NO'
      relay_type: usb_relay
      relay_params: []
    use_router: false
    router_csv: ''
    manual_entries: []
text_case: ''
