Turntable:
  Turntable: RS232Board5
  IP address: 192.168.5.156
  Step: 0,360
  Static dB: ''
  Target RSSI: 45,60
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.50.19
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.56.75
  LDA-908V-8:
    ip_address: 192.168.5.200
    channels: '1'
  model: LDA-908V-8
  step: 0,75:3
rvr:
  iperf:
    path: ''
    server_cmd: iperf -s -i 1
    client_cmd: iperf -c {ip} -i 1 -t 5 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '0'
  tool: iperf
  enable_wpa3: false
router:
  name: asusax86u
  address: 192.168.50.1
text_case: test/performance/test_wifi_peak_throughput.py
debug:
  database_mode: true
  skip_router: false
  skip_corner_rf: false
csv_path: performance_test_csv/rvr_wifi_setup.csv
duration_control:
  loop: ''
  duration_hours: ''
  exitfirst: true
  retry_limit: '2'
check_point:
  ping: true
  ping_targets: 192.168.1.1
cases:
  test_str:
    ac:
      enabled: false
      on_duration: '5'
      off_duration: '5'
      relay_type: usb_relay
      relay_params: []
      port: ''
      mode: 'NO'
    str:
      enabled: true
      on_duration: '15'
      off_duration: '15'
      relay_type: usb_relay
      relay_params: []
      port: COM14 (蓝牙链接上的标准串行 (COM14))
      mode: 'NO'
  test_switch_wifi:
    use_router: false
    router_csv: C:\Users\SH171300-1522\PycharmProjects\wifi_test\config\performance_test_csv\rvr_wifi_setup.csv
    manual_entries:
    - '[{''ssid'': ''SH-AP-052-2g-xts'''
    - '''security_mode'': ''Open System'''
    - '''password'': ''''}]'
