duration_control:
  loop: ''
  duration_hours: ''
  exitfirst: false
  retry_limit: '2'
check_point:
  ping: true
  ping_targets: 192.168.1.1
cases:
  test_switch_wifi_str:
    ac:
      enabled: true
      on_duration: 0
      off_duration: 0
      port: COM5 (蓝牙链接上的标准串行 (COM5))
      mode: 'NO'
    str:
      enabled: true
      on_duration: 0
      off_duration: 0
      port: COM5 (蓝牙链接上的标准串行 (COM5))
      mode: 'NO'
    use_router: false
    router_csv: ''
    manual_entries: []
