duration_control:
  loop: null
  duration_hours: null
  exitfirst: true
  retry_limit: 2
check_point:
  ping: true
  ping_targets: 192.168.1.1
cases:
  test_str:
    ac:
      enabled: false
      on_duration: '5'
      off_duration: '5'
      relay_type: usb_relay
      relay_params: []
      port: ''
      mode: 'NO'
    str:
      enabled: true
      on_duration: '15'
      off_duration: '15'
      relay_type: usb_relay
      relay_params: []
      port: COM14 (蓝牙链接上的标准串行 (COM14))
      mode: 'NO'
  test_switch_wifi:
    use_router: false
    router_csv: performance_test_csv/rvr_wifi_setup.csv
    manual_entries: []
