Turntable:
  Turntable: RS232Board5
  IP address: 192.168.5.156
  Step: 0,360
  Static dB: ''
  Target RSSI: 45,60
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.1.101
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.1.101
  LDA-908V-8:
    ip_address: 192.168.5.200
    channels: '1'
  model: RC4DAT-8G-95
  step: 0,75:3
router:
  name: xiaomibe7000
  address: 192.168.31.1
text_case: test/compatibility/test_compatibility.py
debug:
  database_mode: true
  skip_router: false
  skip_corner_rf: false
csv_path: ''
