duration_control:
  loop: null
  duration_hours: null
  exitfirst: false
  retry_limit: 2
check_point:
  ping: false
  ping_targets: 192.168.1.1
cases:
  test_str:
    ac:
      enabled: false
      on_duration: '5'
      off_duration: '5'
      port: ''
      mode: 'NO'
      relay_type: usb_relay
      relay_params: []
    str:
      enabled: false
      on_duration: '14'
      off_duration: '15'
      port: ''
      mode: 'NO'
      relay_type: usb_relay
      relay_params: []
  test_switch_wifi:
    use_router: false
    router_csv: performance_test_csv/rvr_wifi_setup.csv
    manual_entries: []
text_case: ''
