software_info:
  software_version: ''
  driver_version: ''
hardware_info:
  hardware_version: ''
system:
  version: Android 15
  kernel_version: Kernel 6.1
connect_type:
  Android:
    device: '69512800000000611'
  Linux:
    ip: 192.168.1.102
    wildcard: ''
  third_party:
    enabled: false
    wait_seconds: 45
  type: Linux
project:
  customer: XIAOMI
  product_line: OTT
  project: OB7
  main_chip: S805X3
  wifi_module: W1U
  interface: SDIO
serial_port:
  baud: '9600'
  port: COM14 (蓝牙链接上的标准串行 (COM14))
  status: false
