Turntable:
  Turntable: RS232Board5
  IP address: 192.168.5.156
  Step: 0,360
  Static dB: ''
  Target RSSI: 45,60
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.1.101
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.1.101
  LDA-908V-8:
    ip_address: 192.168.5.200
    channels: '1'
  model: RC4DAT-8G-95
  step: 0,3:1
rvr:
  iperf:
    path: ''
    server_cmd: iperf -s -i 1
    client_cmd: iperf -c {ip} -i 1 -t 5 -P 1
  ixchariot:
    path: D:/Program Files (x86)/Ixia/IxChariot
  repeat: '0'
  throughput_threshold: '0'
  tool: iperf
router:
  name: xiaomibe7000
  address: 192.168.31.1
text_case: test/compatibility/test_compatibility.py
debug:
  database_mode: false
  skip_router: false
  skip_corner_rf: false
csv_path: performance_test_csv/rvr_wifi_setup.csv
