Turntable:
  Turntable: RS232Board5
  IP address: 192.168.5.156
  Step: 0,360
  Static dB: ''
  Target RSSI: 45,60
rf_solution:
  RADIORACK-4-220:
    ip_address: 192.168.1.101
  RC4DAT-8G-95:
    idProduct: '35'
    idVendor: '8398'
    ip_address: 192.168.200.102
  LDA-908V-8:
    ip_address: 192.168.10.43
    channels: 1,2,3,8
  model: LDA-908V-8
  step: 0,75:3
router:
  name: asusax88u
  address: 192.168.10.1
text_case: test/performance/test_wifi_peak_throughput.py
debug:
  database_mode: false
  skip_router: true
  skip_corner_rf: false
csv_path: performance_test_csv/rvr_wifi_setup_demo.csv
